#!/bin/bash
####### this project create by Ali mohamed & the frist day in 19-8-2022######
####### Bash Shell Script Database Management System (DBMS)############
# this option show to user to select 
if [[ ! -d  mydatabase ]]
then
     mkdir mydatabase
     
fi
urls=mydatabase
export PS3="$urls>>"
mypath=`pwd`
export PATH="$PATH:$mypath:$mypath/databases:$mypath/tables"
select item in  "Create Database" "Connect To Databases" "List Databases" "Drop Database"  "Exit"
do 
case $item in
    "Create Database") database_create
    ;;
    "Connect To Databases")
       database_connect 
      
    ;;
    "List Databases") database_list
    ;;
    "Drop Database")  database_drop
          
    ;;
    "Exit")
      break 
      ;;
     *)
      echo "Invild option"
      
      ;; 
esac



done 
