#!/bin/bash
####### this project create by Ali mohamed & the frist day in 19-8-2022######
####### Bash Shell Script Database Management System (DBMS)############
# this option show to user to select 
if [[ ! -d  DBM ]]
then
     mkdir DBM
     
fi
urls=DBM
export PS3="DBM>>"
mypath=`pwd`
export PATH="$PATH:$mypath:$mypath/databases:$mypath/tables"

##########################
check_name()
{
   regex="^[a-zA-Z]{0,100}$" 
    if [[ $1 =~ $regex  && ! -z $1 ]]
    then 
          echo true
    else
         echo false
   fi

}


while true 
do
echo "#########################Main menu #####################################"
echo "1) Create Database"
echo "2) Connect To Databases"
echo "3) List Databases"
echo "4) Drop Database"
echo "5) Exit"
read -r -p "Enter your choise :" input
case $input in
    1) . database_create
    ;;
    2) . database_connect 
      ;;
    3) . database_list
    ;;
    4) . databasedatabase_drop_drop     
    ;;
    5)
      break 
      ;;
     *)
      echo "Invild option"
      
      ;; 
esac



done 
