#!/bin/bash
############ this script connect to database if exit ##################

###this functions check if database exit or not
urls=DBM
check() {
  
  if [[ `check_name $1` = 'true' ]]; then
    if [[ -e "$urls/$1" ]]; then
      read -r -p "Are you sure ? [Y/N or y/n] : " flag
      if [[ $flag = @([Yy]) ]]; then
        rm -r $urls/$1 2>>./.error.log
        if [[ $? == 0 ]]; then
          echo "Database Dropped Successfully"
        else
          echo " no changes "
        fi
      else
        echo " no changes "

      fi
    else
      echo -e "\033[31mDatabase Not found\033[m" 
    fi

  else
    echo -e "\033[31mInvild name of database\033[m" 
  fi
}

read -r -p "Enter your database to Drop :" database_name
check $database_name
