#!/bin/bash
############ this script create  to database if exit ##################

###this functions check if database exit or not
url=DBM
db_create()
{   
     if [[  `check_name $1` = 'true' ]]
     then
      if [[ ! -e $url/$1  ]] 
       then
          mkdir $url/$1 2>>error.log
          mkdir  $url/$1/meta_data 2>>error.log
           mkdir  $url/$1/data 2>>error.log
          echo "created successfully"
       else 
            echo "Error This Database $1 Already Existing "
     fi
else
      echo "invalid Database"
   fi

}
read -p "Enter Database name: " db_name
db_create $db_name

