#!/bin/bash
############ this script connect to database if exit ##################

###this functions check if database exit or not
url=DBM
check()
{
      
     if [[ `check_name $1` = 'true' ]]
      then 
          if [[ -d $urls/$1  && ! -z $urls/$1 ]]
            then
              table_main $url/$1
            
          else
            echo "database is Not Exit"
          fi
      else
          echo "Invild name of database"       
      fi
}
      
     
read -p "Enter your database to connect :" database_name
check $database_name
