#!/bin/bash
############ this script connect to database if exit ##################

###this functions check if database exit or not
urls=$HOME/mydatabase

check()
{
     if [[ -d $urls/$1  && ! -z $urls/$1 ]]
       then
           ../tables/main
     else
        echo "database is Not Exit"
    fi   
}
read -p "Enter your database to connect " database_name
echo $database_name
check $database_name
