#!/bin/bash
############ this script create  to database if exit ##################

###this functions check if database exit or not
urls=$HOME/mydatabase
db_validate()
{
       echo true
}
read -p "Enter Database name: " db_name
 if[[  db_validate $db_name ]]
  then

  fi

