#!/bin/bash
####### this project create by Ali mohamed the frist day in 19-8-2022######
####### Bash Shell Script Database Management System (DBMS)############
# this option show to user to select 
option=("","","","")
select item in  Create\ Table  List\ Tables  Drop\ Table Insert\ into Table  Select\ From Table  Delete\ From Table  Update\ Table
do 
case $item in
    "Create Database") ./databases/database_create
    ;;
    "Connect To Databases") ./databases/database_connect
    ;;
    "List Databases") ./databases/database_list
    ;;
    "Drop Database")  ./databases/database_drop
          
    ;;
    "Exit")
      break 
      ;;
     *)
      echo "Invild option"
      ;; 
esac



done 
