#!/bin/bash
declare -i try=4
if [[ `ls $1/meta_data/ | wc -l ` -gt 0 ]]
then
while [[ $try -gt 0 ]] 
do 
 echo " ######################################## Drop Table Have 4 try ######################################"
 read -r -p "Enter Table Name : " tb_name
  if [[ `check_name $tb_name` = "true"  && -e $1/meta_data/$tb_name ]]
  then
       rm   $1/meta_data/$tb_name 2>>error.log
       rm   $1/data/$tb_name 2>>error.log
        echo   -e "\033[36m"Droped sucessfully"\033[m"
       break
    else
        echo -e "\033[31mEnter valid table\033[m" 
        try=try-1
   fi     
done
else
    echo -e "\033[31m Empty database \033[m" 
fi
