#!/bin/bash

url=$1
check_name()
{
   regex="^[a-zA-Z]" 
    if [[ $1 =~ $regex  && ! -z $1 ]]
    then 
          echo true
    else
         echo false
   fi

}


if [[ $# -eq 1 ]]
  then 
        
        select item in  "Create Table"  "List Tables"  "Drop Table"  "Insert into Table"  "Select From Table"  "Delete From Table"  "Update Table" "Exit"
        do 
        case $item in
            "Create Table") . table_create $url
            ;;
            "List Tables") . table_list $url
            ;;
            "Drop Table") . table_drop $url
              
            ;;
            "Insert into Table")  . table_insert $url
                  
            ;;
            "Select From Table")  . table_select $url
                  
            ;;
            "Delete From Table")  . table_delete $url
                  
            ;;
            "Update Table")  . table_update $url
                  
            ;;
            "Exit")
              break 
              ;;
            *)
              echo "Invild option"
              ;; 
        esac



        done 

  fi

