#!/bin/bash
url=$1
clear
check_name()
{
   regex="^[a-zA-Z]{0,100}$" 
    if [[ $1 =~ [[:space:]] ]]; then
            echo false
      else
            if [[ $1 =~ $regex && ! -z $1 ]]; then
                  echo true
            else
                  echo false
            fi
      fi

}

if [[ $# -eq 1 ]]
  then 
        
        while true
        do 
        echo    "+------------------------------------------------------------------+"
        echo -e "                  DataBase Name: $url                          "
        echo    "+-------------------- Table Main manu -----------------------------+"
        echo "1) Create Table"
        echo "2) List Tables"
        echo "3) Drop Table"
        echo "4) Insert into Table"
        echo "5) Select From Table"
        echo "6) Delete from Table"
        echo "7) Update Table"
        echo "8) Clear "
        echo "9) Exit"
            echo    "+------------------------------------------------------------------+"

        read -r -p "Enter your choise : " input
        case $input in
            1) . table_create $url
            ;;
            2) . table_list $url
            ;;
            3) . table_drop $url 
            ;;
            4)  . table_insert $url     
            ;;
            5)  . table_select $url     
            ;;
            6)  . table_delete $url     
            ;;
            7)  . table_update $url     
            ;;
            8)
              clear 
              ;;
               9)
              break 
              ;;
            *)
             echo -e "\033[31m Enter valid option \033[m" 
              ;; 
        esac



        done 

  fi

