#!/bin/bash
###############Insert Data in Table##############################
url=$1
clear
file_index=()
declare -i i=0
declare -i index=1
declare -i try=4
data=''
while [[ $try -gt 0 ]]; do
  echo "+--------------------------------------Insert Table------------------------------+"
  read -r -p "Enter Table name :" tb_name
  if [[ `check_name "$tb_name"` = "true"  && -e $1/meta_data/$tb_name ]]
  then
          declare -i num_field=`cat $1/meta_data/$tb_name | wc -l`-1 #number of filed
            for colum in $(awk -F: '{ print $1 }' $1/meta_data/$tb_name); do
              if [[ `cut -d : -f 1  $1/meta_data/$tb_name | head -1 ` = $colum  ]]; then 
                # check if deplicate primary key beagin
                while true; do
                  read -r -p "please Enter $colum :" input
                  if [[  "$(cut -d : -f 1 $1/data/$tb_name | grep $input | head -1)" = $input  ]]; then
                     echo -e "\033[31mdeplicate primary key Enter anther key\033[m" 
                  else
                    if [[ ! $num_field -eq 1 ]]
                     then
                        data+="$input:"
                        num_field=num_field-1
                        break
                     else 
                         data+="$input"
                        num_field=num_field-1
                        break
                    fi    

                  fi
                done
                # end check deplicate
              else
                read -r -p "please Enter $colum :" input
                num_field=num_field-1
                if [[  $num_field  -gt 0 ]]; then
                    data+="$input:"   
                    index=index+1
                else
                  data+="$input"
                  break
                fi
              fi
            done
            break
       
  else
  
            echo -e "\033[31mEnter valid table \033[m" 
            try=try-1
  fi
done
  
if [[ ! -z $data ]]
      then 
      echo $data >>$1/data/$tb_name
       echo   -e "\033[36mtable updated successfully\033[m"
      fi
 